Repository unofficial-skills/alpha-video, pull requests merged in 2021-06, with the labels that each got.

#46 Update README.md
  README.md
Labels: automerge, completed

#47 Delete .test directory
  .test/#
  .test/Dockerfile
Labels: ready

#44 Nginx proxy manager
  README.md
  docs/unraid-os.md
  edits/signatures/version1/cla.json
  static/img/port-photo.PNG
  static/img/ssl.PNG
Labels: completed

#50 Community Host Program
  docs/start.md
Labels: ready

#52 Add Cloud support
  docs/alternative.md
  docs/aws.md
  docs/heroku.md
  sidebars.js
Labels: ready

#55 FOUNDERS BETA PROGRAM
  docs/contributions.md
Labels: ready

#56 Fix echo icon
  src/pages/index.js
  static/img/Echo_Show.svg
Labels: ready

#57 Rename unraid os to unraid
  docs/alternative.md
  docs/unraid-os.md
  sidebars.js
Labels: completed

#59 windows update
  thealphavideo/requirements.txt
  thealphavideo/ui.py
  thealphavideo/windows-alpha-video.py
Labels: completed, ready

#62 i18n
  .gitignore
  config/.spellcheck.yml
  docusaurus.config.js
  i18n/fr/code.json
  i18n/fr/docusaurus-plugin-content-docs/current.json
  i18n/fr/docusaurus-theme-classic/footer.json
  i18n/fr/docusaurus-theme-classic/navbar.json
  package-lock.json
  package.json
  sidebars.js
  src/components/HomepageFeatures.js
  src/components/HomepageFeatures.module.css
  src/css/custom.css
  src/pages/index.js
  src/pages/index.module.css
  src/pages/markdown-page.md
  static/.nojekyll
  static/CNAME
  static/img/277-2770938_amazon-echo-show-echo-show-transparent-clipart.svg
  static/img/Echo_Show.svg
  static/img/YouTube_Logo_2017.svg
  static/img/api-startnew.PNG
  static/img/click-new-project.PNG
  static/img/config.PNG
  static/img/docusaurus.png
  static/img/favicon.ico
  static/img/logo.svg
  static/img/port-photo.PNG
  static/img/set.PNG
  static/img/ssl.PNG
  static/img/tutorial/docsVersionDropdown.png
  static/img/tutorial/localeDropdown.png
  static/img/upload-project.PNG
  static/img/upload.PNG
  static/img/voiceflow.svg
  static/public.html
  static/update.txt
  yarn.lock
Labels: completed, ready

#63 Added German Translation for Unraid-Docs
  i18n/de/docusaurus-plugin-content-docs/current/unraid-os.md
Labels: Translation
